### ISSUE TITLE
Add support for Azure Files

### ISSUE THREAD

**Issue by richstep** [formulahendry/vscode-azure-storage-explorer#2]

**Comment by formulahendry** [comment]
@richstep , I have added support for Azure Files with below functions:

  * List File Shares
  * Create File Shares
  * Delete File Shares
  * List Directories and Files
  * Create Directory
  * Delete Directory
  * Download File
  * Upload File
  * Delete File

Please install the latest version and have a try. Let me know if you have any other feature request or feedback.
